stages:
  - lint
  - build
  - test

variables:
  IMAGE_NAME: $DOCKERHUB_USERNAME/zol-hw3:latest

image: docker:latest

lint:
  stage: lint
  image: python:3.9
  script:
    - pip install flake8
    - flake8 .

build_image:
  stage: build
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t $IMAGE_NAME -f Dockerfile .
    - docker push $IMAGE_NAME

test:
  stage: test
  script:
    - docker pull $IMAGE_NAME
    - docker run $IMAGE_NAME sh -c "pytest tests/*"
