version: '3.9'

services:
  minio:
    image: minio/minio
    container_name: minio_s3
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  api:
    image: zolotarevstat/mlops:v1.0
    container_name: api
    restart: always
    depends_on:
      - minio
    ports:
      - "8877:7755"
    volumes:
      - ./src:/app/src
      - ./init.sh:/app/init.sh

